name: .NET CI/CD to Render

on:
  push:
    branches:
      - dev
      - uat
      - main
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output publish_output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish_output
          path: publish_output

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish_output
          path: publish_output

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering deployment on Render..."
          
          # Trigger deployment
          DEPLOY_RESPONSE=$(curl -s -X POST https://api.render.com/deploy/srv-d5fnbp2li9vc738sh54g \
            -H "Authorization: Bearer $RENDER_API_KEY")
          
          DEPLOY_ID=$(echo "$DEPLOY_RESPONSE" | jq -r '.id')
          if [ -z "$DEPLOY_ID" ] || [ "$DEPLOY_ID" == "null" ]; then
            echo "❌ Failed to trigger deployment."
            exit 1
          fi
          
          echo "Deployment triggered. ID: $DEPLOY_ID"
          
          # Poll deployment status
          STATUS=""
          MAX_RETRIES=30
          RETRY_INTERVAL=10

          for i in $(seq 1 $MAX_RETRIES); do
            STATUS=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
              https://api.render.com/deploy/srv-d5fnbp2li9vc738sh54g/deploys/$DEPLOY_ID | jq -r '.status')
            
            echo "Deployment status: $STATUS"

            if [ "$STATUS" == "succeeded" ]; then
              echo "✅ Deployment completed successfully!"
              exit 0
            elif [ "$STATUS" == "failed" ]; then
              echo "❌ Deployment failed."
              exit 1
            fi

            sleep $RETRY_INTERVAL
          done

          echo "❌ Deployment did not complete within expected time."
          exit 1
